apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: native-lb-ing
spec:
  backend:
    serviceName: native-lb-svc # Name of the Service targeted by the Ingress
    servicePort: 80 # Should match the port used by the Service
